#!/bin/bash

sudo apt install python3-venv
python3 -m venv venv
source venv/bin/activate
#session may not be needed
pip3 install Flask
pip3 install Flask-Session
pip3 install requests
pip3 install Flask-SocketIO
pip3 install eventlet
